# Generated by Django 5.2.1 on 2025-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id_deceased', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateTimeField()),
                ('date_death', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
                ('burial_place', models.CharField(max_length=100)),
                ('visualization_state', models.BooleanField()),
                ('visualization_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_DECEASED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeceasedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'TBL_DECEASED_IMAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeceasedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'TBL_DECEASED_VIDEO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_link', models.CharField(max_length=1000)),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_IMAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id_metadata', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('coordinates', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_IMAGE_METADATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'TBL_NOTIFICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id_qr', models.BigAutoField(primary_key=True, serialize=False)),
                ('qr_code', models.BigIntegerField(unique=True)),
                ('visualization_status', models.CharField(max_length=50)),
                ('generation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'TBL_QR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'TBL_RELATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('relationship', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TBL_RELATIONSHIP_TYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField()),
                ('request_type', models.CharField(max_length=50)),
                ('request_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TBL_REQUEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'TBL_USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDeceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_relation', models.DateTimeField()),
                ('has_permission', models.BooleanField()),
            ],
            options={
                'db_table': 'TBL_USER_DECEASED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_link', models.CharField(max_length=1000)),
                ('event_title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_VIDEO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id_metadata', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('coordinates', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TBL_VIDEO_METADATA',
                'managed': False,
            },
        ),
    ]
